variable "create_ssh" {}
variable "prefix" {}
variable "vpc_id" {}
variable "default_tags" {}
variable "tags" {}
variable "security_group" {}
variable "subnet_ids" {}
variable "ssh_pubkey" {}
variable "admins_id" {}
variable "read_only_id" {}
