# =============================================================================
# DATA SOURCES
# =============================================================================
# This file contains all external data source declarations used by the 
# StrongDM onboarding modules. Data sources are used to query existing
# AWS resources and StrongDM organization information.
#
# Key Functions:
#   - AWS VPC/subnet discovery for existing infrastructure
#   - StrongDM SSH CA public key retrieval
#   - Existing StrongDM user account lookups
# =============================================================================

# -----------------------------------------------------------------------------
# AWS NETWORKING DATA SOURCES
# -----------------------------------------------------------------------------
# These data sources gather VPC and subnet information when using existing
# AWS infrastructure instead of creating new networking resources.

# Default or explicitly specified VPC lookup
# Only executed when create_vpc = false to avoid unnecessary API calls
data "aws_vpc" "default" {
  count = var.create_vpc ? 0 : 1

  # Use explicitly provided vpc_id or discover default VPC
  id      = var.vpc_id
  default = var.vpc_id == null
}

# Subnet discovery within the selected VPC
# Finds all available subnets for resource placement when not creating new VPC
data "aws_subnets" "subnets" {
  count = var.create_vpc ? 0 : 1

  filter {
    name   = "vpc-id"
    values = [local.vpc_id]
  }
}

# -----------------------------------------------------------------------------
# STRONGDM ORGANIZATION DATA SOURCES  
# -----------------------------------------------------------------------------
# These data sources retrieve StrongDM-specific information for the
# authenticated organization and user account integration.

# SSH Certificate Authority public key
# Required for SSH certificate-based authentication to resources
# This key is automatically generated by StrongDM for each organization
data "sdm_ssh_ca_pubkey" "this_key" {}

# Existing StrongDM user account lookups
# Retrieves user account information for granting resource access
# Only executed for users specified in grant_to_existing_users variable
data "sdm_account" "existing_users" {
  count = length(var.grant_to_existing_users)

  type  = "user"
  email = var.grant_to_existing_users[count.index]
}
